const CITIES_DATA = [
  { name: 'Aracaju, SE',             query: 'Aracaju, Sergipe, Brasil' },
  { name: 'Belém, PA',               query: 'Belém, Pará, Brasil' },
  { name: 'Belo Horizonte, MG',      query: 'Belo Horizonte, Minas Gerais, Brasil' },
  { name: 'Boa Vista, RR',           query: 'Boa Vista, Roraima, Brasil' },
  { name: 'Brasília, DF',            query: 'Brasília, Distrito Federal, Brasil' },
  { name: 'Campinas, SP',            query: 'Campinas, São Paulo, Brasil' },
  { name: 'Campo Grande, MS',        query: 'Campo Grande, Mato Grosso do Sul, Brasil' },
  { name: 'Caruaru, PE',             query: 'Caruaru, Pernambuco, Brasil' },
  { name: 'Caxias do Sul, RS',       query: 'Caxias do Sul, Rio Grande do Sul, Brasil' },
  { name: 'Cuiabá, MT',              query: 'Cuiabá, Mato Grosso, Brasil' },
  { name: 'Curitiba, PR',            query: 'Curitiba, Paraná, Brasil' },
  { name: 'Feira de Santana, BA',    query: 'Feira de Santana, Bahia, Brasil' },
  { name: 'Florianópolis, SC',       query: 'Florianópolis, Santa Catarina, Brasil' },
  { name: 'Fortaleza, CE',           query: 'Fortaleza, Ceará, Brasil' },
  { name: 'Goiânia, GO',             query: 'Goiânia, Goiás, Brasil' },
  { name: 'João Pessoa, PB',         query: 'João Pessoa, Paraíba, Brasil' },
  { name: 'Joinville, SC',           query: 'Joinville, Santa Catarina, Brasil' },
  { name: 'Juazeiro do Norte, CE',   query: 'Juazeiro do Norte, Ceará, Brasil' },
  { name: 'Londrina, PR',            query: 'Londrina, Paraná, Brasil' },
  { name: 'Macapá, AP',              query: 'Macapá, Amapá, Brasil' },
  { name: 'Maceió, AL',              query: 'Maceió, Alagoas, Brasil' },
  { name: 'Manaus, AM',              query: 'Manaus, Amazonas, Brasil' },
  { name: 'Maringá, PR',             query: 'Maringá, Paraná, Brasil' },
  { name: 'Mossoró, RN',             query: 'Mossoró, Rio Grande do Norte, Brasil' },
  { name: 'Natal, RN',               query: 'Natal, Rio Grande do Norte, Brasil' },
  { name: 'Palmas, TO',              query: 'Palmas, Tocantins, Brasil' },
  { name: 'Porto Alegre, RS',        query: 'Porto Alegre, Rio Grande do Sul, Brasil' },
  { name: 'Porto Velho, RO',         query: 'Porto Velho, Rondônia, Brasil' },
  { name: 'Recife, PE',              query: 'Recife, Pernambuco, Brasil' },
  { name: 'Ribeirão Preto, SP',      query: 'Ribeirão Preto, São Paulo, Brasil' },
  { name: 'Rio Branco, AC',          query: 'Rio Branco, Acre, Brasil' },
  { name: 'Rio de Janeiro, RJ',      query: 'Rio de Janeiro, Rio de Janeiro, Brasil' },
  { name: 'Salvador, BA',            query: 'Salvador, Bahia, Brasil' },
  { name: 'Santos, SP',              query: 'Santos, São Paulo, Brasil' },
  { name: 'São José dos Campos, SP', query: 'São José dos Campos, São Paulo, Brasil' },
  { name: 'São Luís, MA',            query: 'São Luís, Maranhão, Brasil' },
  { name: 'São Paulo, SP',           query: 'São Paulo, São Paulo, Brasil' },
  { name: 'Sorocaba, SP',            query: 'Sorocaba, São Paulo, Brasil' },
  { name: 'Teresina, PI',            query: 'Teresina, Piauí, Brasil' },
  { name: 'Uberlândia, MG',          query: 'Uberlândia, Minas Gerais, Brasil' },
  { name: 'Vitória, ES',             query: 'Vitória, Espírito Santo, Brasil' },
];
